version: '3.4'
services:
  frontend:
    image: ${CONTAINER_REGISTRY_BASE}/frontend:${CONTAINER_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      args:
        BUILD_STORYBOOK: ${NEXT_PUBLIC_BUILD_STORYBOOK}
    ports:
      - '8888:80'
