version: '3.4'
services:
  frontend:
    env_file: 
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend_dev
    ports:
      - '3000:3000'
    volumes:
      - ./:/app:rw,cached
